openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8081
    description: Generated server url
paths:
  /api/book/{id}:
    $ref: paths/api_book_{id}.yaml
  /api/book/:
    $ref: paths/api_book_.yaml
